In [6]:
import numpy as np

from ztbiocas.online import covariance as cov

In [15]:
# x = np.random.rand(4, 3)
x = np.arange(400, dtype=np.float32).reshape((4, 100))
print(np.mean(x, axis=1))
print(np.cov(x))

[ 49.5 149.5 249.5 349.5]
[[841.66666667 841.66666667 841.66666667 841.66666667]
 [841.66666667 841.66666667 841.66666667 841.66666667]
 [841.66666667 841.66666667 841.66666667 841.66666667]
 [841.66666667 841.66666667 841.66666667 841.66666667]]


In [16]:
avgx, covx, n_seen = cov.cov_online(x)
print(avgx)
print(covx)
print(n_seen)

[ 50. 150. 250. 350.]
[[820.8825 820.8825 820.8825 820.8825]
 [820.8825 820.8825 820.8825 820.8825]
 [820.8825 820.8825 820.8825 820.8825]
 [820.8825 820.8825 820.8825 820.8825]]
100
